# services:
#   mysql:
#     image: mysql:8.0
#     container_name: bankapp-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: Test@123
#       MYSQL_DATABASE: bankappdb
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTest@123"]
#       interval: 30s
#       timeout: 5s
#       retries: 5
#       start_period: 30s
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql-data:/var/lib/mysql
#     networks:
#       - bankapp-new

#   bankapp:
#     build: .
#     container_name: bankapp
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_DATASOURCE_URL: jdbc:mysql://bankapp-mysql:3306/bankappdb
#       SPRING_DATASOURCE_USERNAME: root
#       SPRING_DATASOURCE_PASSWORD: Test@123
#     depends_on:
#       mysql:
#         condition: service_healthy
#       ollama:
#         condition: service_healthy
#     networks:
#       - bankapp-new
  
#   ollama:
#     image: llama/ollama
#     container_name: ollama
#     ports:
#       - "11434:11434"
#     networks:
#       - bankapp-new
# networks:
#   bankapp-new:
#     driver: bridge

# volumes:
#   mysql-data:

version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bankapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pTest@123"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-new

  bankapp:
    build: avnish2/ai-bankapp:latest
    container_name: bankapp
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: bankapp-mysql
      MYSQL_PORT: "3306"
      MYSQL_DATABASE: bankappdb
      MYSQL_USER: root
      MYSQL_PASSWORD: Test@123
      OLLAMA_URL: http://ollama:11434
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - bankapp-new

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - bankapp-new

networks:
  bankapp-new:
    driver: bridge

volumes:
  mysql-data:
  ollama_data:
